### ISSUE TITLE
Fix github action trigger

### ISSUE THREAD

**Issue by nick-bisonai** [Bisonai/orakl#1107]
https://github.com/Bisonai/orakl/actions/workflows/contracts.test.yaml
seen from github action, it was kept triggered with unrelated path updates

In official docs for github actions (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore), it's written as followed

`If you define both branches/branches-ignore and paths/paths-ignore, the workflow will only run when both filters are satisfied`

yet, trigger defined as followed in contracts.test.yaml seems to be running all the time whenever there's a updates on different branches. even when there's an update in files not in contracts folder

```
on:
  push:
    branches-ignore:
      - "master"
    paths:
      - "contracts-v0.1/**"
      - "!contracts-v0.1/**/VRFCoordinator.sol"
      - "!contracts-v0.1/**/VRFConsumerBase.sol"
      - "!contracts-v0.1/**/vrf/**"
```

<img width="880" alt="image" src="https://github.com/Bisonai/orakl/assets/148735107/14d0ebd3-4bf1-4247-9818-283088633999">
<img width="875" alt="image" src="https://github.com/Bisonai/orakl/assets/148735107/de4e3235-eca9-4572-bc81-49235e37bf08">

and paths are also defined as written in official docs
(https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths)

![Image](https://github.com/Bisonai/orakl/assets/148735107/3a883018-5e7b-460f-8a83-d67e603c4419)
