### ISSUE TITLE
Add slack notification into reusable GCP public workflow

### ISSUE THREAD

**Issue by jay-kim-kor** [Bisonai/orakl#1156]
- How to send Slack noti. in GH actions
  ```yaml
  - name: Notify success on Slack
    if: ${{ success() }}
    uses: rtCamp/action-slack-notify@master
    env:
      SLACK_CHANNEL: "#_deploy-notifications "
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_USERNAME: Github Actions
      SLACK_ICON: https://raw.githubusercontent.com/therne/actions-slack/master/assets/profile.png
      MSG_MINIMAL: true
      SITE_TITLE: Endpoint
      SITE_NAME: ${{ steps.meta.outputs.branch == 'main' && 'api.factto.xyz' || 'api.dev.factto.xyz' }}
      HOST_TITLE: Commit SHA
      HOST_NAME: ${{ steps.meta.outputs.short_sha }}
      SLACK_TITLE: PR Title
      SLACK_MESSAGE: ${{ github.event.pull_request.title }}
      SLACK_FOOTER: Github Actions | <https://github.com/${{ github.repository }}|${{ github.repository }} on ${{ steps.meta.outputs.branch }}>

  - name: Notify failure on Slack
    if: ${{ failure() }}
    uses: rtCamp/action-slack-notify@master
    env:
      SLACK_CHANNEL: "#_deploy-notifications "
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_USERNAME: Github Actions
      SLACK_ICON: https://raw.githubusercontent.com/therne/actions-slack/master/assets/profile.png
      SLACK_COLOR: danger
      SLACK_TITLE: PR Title
      SLACK_MESSAGE: ${{ github.event.pull_request.title }}
      SLACK_FOOTER: Github Actions | <https://github.com/${{ github.repository }}|${{ github.repository }} on ${{ steps.meta.outputs.branch }}>
  ```
- Reusable workflow: [docs](https://docs.github.com/en/actions/using-workflows/reusing-workflows)
